use_map_topic: true
first_map_only: false

odom_model_type: omni

odom_alpha1: 0.05
odom_alpha2: 0.05
odom_alpha3: 0.05
odom_alpha4: 0.05
odom_alpha5: 0.10

transform_tolerance: 0.3
gui_publish_rate: 20.0
save_pose_rate: 0.5

laser_model_type: likelihood_field
laser_max_beams: 180
laser_max_range: 8.0
laser_min_range: 0.05
laser_likelihood_max_dist: 3.0

laser_z_hit: 0.95
laser_z_short: 0.02
laser_z_max: 0.01
laser_z_rand: 0.02
laser_sigma_hit: 0.10
laser_lambda_short: 0.1

min_particles: 1000
max_particles: 3000
kld_err: 0.02
kld_z: 0.99

update_min_d: 0.01
update_min_a: 0.01
resample_interval: 1
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0

odom_frame_id: "odom"
base_frame_id: "base_link"
global_frame_id: "map"

tf_broadcast: true