// Generated by gencpp from file webots_ros/node_get_contact_pointsRequest.msg
// DO NOT EDIT!


#ifndef WEBOTS_ROS_MESSAGE_NODE_GET_CONTACT_POINTSREQUEST_H
#define WEBOTS_ROS_MESSAGE_NODE_GET_CONTACT_POINTSREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace webots_ros
{
template <class ContainerAllocator>
struct node_get_contact_pointsRequest_
{
  typedef node_get_contact_pointsRequest_<ContainerAllocator> Type;

  node_get_contact_pointsRequest_()
    : node(0)
    , include_descendants(false)  {
    }
  node_get_contact_pointsRequest_(const ContainerAllocator& _alloc)
    : node(0)
    , include_descendants(false)  {
  (void)_alloc;
    }



   typedef uint64_t _node_type;
  _node_type node;

   typedef uint8_t _include_descendants_type;
  _include_descendants_type include_descendants;





  typedef boost::shared_ptr< ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct node_get_contact_pointsRequest_

typedef ::webots_ros::node_get_contact_pointsRequest_<std::allocator<void> > node_get_contact_pointsRequest;

typedef boost::shared_ptr< ::webots_ros::node_get_contact_pointsRequest > node_get_contact_pointsRequestPtr;
typedef boost::shared_ptr< ::webots_ros::node_get_contact_pointsRequest const> node_get_contact_pointsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator1> & lhs, const ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.node == rhs.node &&
    lhs.include_descendants == rhs.include_descendants;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator1> & lhs, const ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace webots_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c4df127c770c26f94b8cdc3c61f1dc0";
  }

  static const char* value(const ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c4df127c770c26fULL;
  static const uint64_t static_value2 = 0x94b8cdc3c61f1dc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "webots_ros/node_get_contact_pointsRequest";
  }

  static const char* value(const ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 node\n"
"bool include_descendants\n"
;
  }

  static const char* value(const ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node);
      stream.next(m.include_descendants);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct node_get_contact_pointsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::webots_ros::node_get_contact_pointsRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "node: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.node);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "include_descendants: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.include_descendants);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEBOTS_ROS_MESSAGE_NODE_GET_CONTACT_POINTSREQUEST_H
