// Generated by gencpp from file webots_ros/node_disable_contact_points_tracking.msg
// DO NOT EDIT!


#ifndef WEBOTS_ROS_MESSAGE_NODE_DISABLE_CONTACT_POINTS_TRACKING_H
#define WEBOTS_ROS_MESSAGE_NODE_DISABLE_CONTACT_POINTS_TRACKING_H

#include <ros/service_traits.h>


#include <webots_ros/node_disable_contact_points_trackingRequest.h>
#include <webots_ros/node_disable_contact_points_trackingResponse.h>


namespace webots_ros
{

struct node_disable_contact_points_tracking
{

typedef node_disable_contact_points_trackingRequest Request;
typedef node_disable_contact_points_trackingResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_disable_contact_points_tracking
} // namespace webots_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_ros::node_disable_contact_points_tracking > {
  static const char* value()
  {
    return "594d3b785623c78d3382c6628faa0f8c";
  }

  static const char* value(const ::webots_ros::node_disable_contact_points_tracking&) { return value(); }
};

template<>
struct DataType< ::webots_ros::node_disable_contact_points_tracking > {
  static const char* value()
  {
    return "webots_ros/node_disable_contact_points_tracking";
  }

  static const char* value(const ::webots_ros::node_disable_contact_points_tracking&) { return value(); }
};


// service_traits::MD5Sum< ::webots_ros::node_disable_contact_points_trackingRequest> should match
// service_traits::MD5Sum< ::webots_ros::node_disable_contact_points_tracking >
template<>
struct MD5Sum< ::webots_ros::node_disable_contact_points_trackingRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_ros::node_disable_contact_points_tracking >::value();
  }
  static const char* value(const ::webots_ros::node_disable_contact_points_trackingRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_ros::node_disable_contact_points_trackingRequest> should match
// service_traits::DataType< ::webots_ros::node_disable_contact_points_tracking >
template<>
struct DataType< ::webots_ros::node_disable_contact_points_trackingRequest>
{
  static const char* value()
  {
    return DataType< ::webots_ros::node_disable_contact_points_tracking >::value();
  }
  static const char* value(const ::webots_ros::node_disable_contact_points_trackingRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_ros::node_disable_contact_points_trackingResponse> should match
// service_traits::MD5Sum< ::webots_ros::node_disable_contact_points_tracking >
template<>
struct MD5Sum< ::webots_ros::node_disable_contact_points_trackingResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_ros::node_disable_contact_points_tracking >::value();
  }
  static const char* value(const ::webots_ros::node_disable_contact_points_trackingResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_ros::node_disable_contact_points_trackingResponse> should match
// service_traits::DataType< ::webots_ros::node_disable_contact_points_tracking >
template<>
struct DataType< ::webots_ros::node_disable_contact_points_trackingResponse>
{
  static const char* value()
  {
    return DataType< ::webots_ros::node_disable_contact_points_tracking >::value();
  }
  static const char* value(const ::webots_ros::node_disable_contact_points_trackingResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_ROS_MESSAGE_NODE_DISABLE_CONTACT_POINTS_TRACKING_H
