// Generated by gencpp from file webots_ros/node_enable_pose_trackingRequest.msg
// DO NOT EDIT!


#ifndef WEBOTS_ROS_MESSAGE_NODE_ENABLE_POSE_TRACKINGREQUEST_H
#define WEBOTS_ROS_MESSAGE_NODE_ENABLE_POSE_TRACKINGREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace webots_ros
{
template <class ContainerAllocator>
struct node_enable_pose_trackingRequest_
{
  typedef node_enable_pose_trackingRequest_<ContainerAllocator> Type;

  node_enable_pose_trackingRequest_()
    : node(0)
    , sampling_period(0)
    , from_node(0)  {
    }
  node_enable_pose_trackingRequest_(const ContainerAllocator& _alloc)
    : node(0)
    , sampling_period(0)
    , from_node(0)  {
  (void)_alloc;
    }



   typedef uint64_t _node_type;
  _node_type node;

   typedef int32_t _sampling_period_type;
  _sampling_period_type sampling_period;

   typedef uint64_t _from_node_type;
  _from_node_type from_node;





  typedef boost::shared_ptr< ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> const> ConstPtr;

}; // struct node_enable_pose_trackingRequest_

typedef ::webots_ros::node_enable_pose_trackingRequest_<std::allocator<void> > node_enable_pose_trackingRequest;

typedef boost::shared_ptr< ::webots_ros::node_enable_pose_trackingRequest > node_enable_pose_trackingRequestPtr;
typedef boost::shared_ptr< ::webots_ros::node_enable_pose_trackingRequest const> node_enable_pose_trackingRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator1> & lhs, const ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator2> & rhs)
{
  return lhs.node == rhs.node &&
    lhs.sampling_period == rhs.sampling_period &&
    lhs.from_node == rhs.from_node;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator1> & lhs, const ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace webots_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "acb2c210846725d8c180a233b1c72648";
  }

  static const char* value(const ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xacb2c210846725d8ULL;
  static const uint64_t static_value2 = 0xc180a233b1c72648ULL;
};

template<class ContainerAllocator>
struct DataType< ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "webots_ros/node_enable_pose_trackingRequest";
  }

  static const char* value(const ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint64 node\n"
"int32 sampling_period\n"
"uint64 from_node\n"
;
  }

  static const char* value(const ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.node);
      stream.next(m.sampling_period);
      stream.next(m.from_node);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct node_enable_pose_trackingRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::webots_ros::node_enable_pose_trackingRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "node: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.node);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "sampling_period: ";
    Printer<int32_t>::stream(s, indent + "  ", v.sampling_period);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "from_node: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.from_node);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEBOTS_ROS_MESSAGE_NODE_ENABLE_POSE_TRACKINGREQUEST_H
