// Generated by gencpp from file webots_ros/node_get_pose.msg
// DO NOT EDIT!


#ifndef WEBOTS_ROS_MESSAGE_NODE_GET_POSE_H
#define WEBOTS_ROS_MESSAGE_NODE_GET_POSE_H

#include <ros/service_traits.h>


#include <webots_ros/node_get_poseRequest.h>
#include <webots_ros/node_get_poseResponse.h>


namespace webots_ros
{

struct node_get_pose
{

typedef node_get_poseRequest Request;
typedef node_get_poseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_pose
} // namespace webots_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_ros::node_get_pose > {
  static const char* value()
  {
    return "c971ec247720786da5fd4aa095defd52";
  }

  static const char* value(const ::webots_ros::node_get_pose&) { return value(); }
};

template<>
struct DataType< ::webots_ros::node_get_pose > {
  static const char* value()
  {
    return "webots_ros/node_get_pose";
  }

  static const char* value(const ::webots_ros::node_get_pose&) { return value(); }
};


// service_traits::MD5Sum< ::webots_ros::node_get_poseRequest> should match
// service_traits::MD5Sum< ::webots_ros::node_get_pose >
template<>
struct MD5Sum< ::webots_ros::node_get_poseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_ros::node_get_pose >::value();
  }
  static const char* value(const ::webots_ros::node_get_poseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_ros::node_get_poseRequest> should match
// service_traits::DataType< ::webots_ros::node_get_pose >
template<>
struct DataType< ::webots_ros::node_get_poseRequest>
{
  static const char* value()
  {
    return DataType< ::webots_ros::node_get_pose >::value();
  }
  static const char* value(const ::webots_ros::node_get_poseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_ros::node_get_poseResponse> should match
// service_traits::MD5Sum< ::webots_ros::node_get_pose >
template<>
struct MD5Sum< ::webots_ros::node_get_poseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_ros::node_get_pose >::value();
  }
  static const char* value(const ::webots_ros::node_get_poseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_ros::node_get_poseResponse> should match
// service_traits::DataType< ::webots_ros::node_get_pose >
template<>
struct DataType< ::webots_ros::node_get_poseResponse>
{
  static const char* value()
  {
    return DataType< ::webots_ros::node_get_pose >::value();
  }
  static const char* value(const ::webots_ros::node_get_poseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_ROS_MESSAGE_NODE_GET_POSE_H
