// Generated by gencpp from file webots_ros/node_get_field_by_index.msg
// DO NOT EDIT!


#ifndef WEBOTS_ROS_MESSAGE_NODE_GET_FIELD_BY_INDEX_H
#define WEBOTS_ROS_MESSAGE_NODE_GET_FIELD_BY_INDEX_H

#include <ros/service_traits.h>


#include <webots_ros/node_get_field_by_indexRequest.h>
#include <webots_ros/node_get_field_by_indexResponse.h>


namespace webots_ros
{

struct node_get_field_by_index
{

typedef node_get_field_by_indexRequest Request;
typedef node_get_field_by_indexResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_field_by_index
} // namespace webots_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_ros::node_get_field_by_index > {
  static const char* value()
  {
    return "24bbfc7fa321c886f58114d630e6f1fb";
  }

  static const char* value(const ::webots_ros::node_get_field_by_index&) { return value(); }
};

template<>
struct DataType< ::webots_ros::node_get_field_by_index > {
  static const char* value()
  {
    return "webots_ros/node_get_field_by_index";
  }

  static const char* value(const ::webots_ros::node_get_field_by_index&) { return value(); }
};


// service_traits::MD5Sum< ::webots_ros::node_get_field_by_indexRequest> should match
// service_traits::MD5Sum< ::webots_ros::node_get_field_by_index >
template<>
struct MD5Sum< ::webots_ros::node_get_field_by_indexRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_ros::node_get_field_by_index >::value();
  }
  static const char* value(const ::webots_ros::node_get_field_by_indexRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_ros::node_get_field_by_indexRequest> should match
// service_traits::DataType< ::webots_ros::node_get_field_by_index >
template<>
struct DataType< ::webots_ros::node_get_field_by_indexRequest>
{
  static const char* value()
  {
    return DataType< ::webots_ros::node_get_field_by_index >::value();
  }
  static const char* value(const ::webots_ros::node_get_field_by_indexRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_ros::node_get_field_by_indexResponse> should match
// service_traits::MD5Sum< ::webots_ros::node_get_field_by_index >
template<>
struct MD5Sum< ::webots_ros::node_get_field_by_indexResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_ros::node_get_field_by_index >::value();
  }
  static const char* value(const ::webots_ros::node_get_field_by_indexResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_ros::node_get_field_by_indexResponse> should match
// service_traits::DataType< ::webots_ros::node_get_field_by_index >
template<>
struct DataType< ::webots_ros::node_get_field_by_indexResponse>
{
  static const char* value()
  {
    return DataType< ::webots_ros::node_get_field_by_index >::value();
  }
  static const char* value(const ::webots_ros::node_get_field_by_indexResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_ROS_MESSAGE_NODE_GET_FIELD_BY_INDEX_H
