// Generated by gencpp from file webots_ros/node_get_string.msg
// DO NOT EDIT!


#ifndef WEBOTS_ROS_MESSAGE_NODE_GET_STRING_H
#define WEBOTS_ROS_MESSAGE_NODE_GET_STRING_H

#include <ros/service_traits.h>


#include <webots_ros/node_get_stringRequest.h>
#include <webots_ros/node_get_stringResponse.h>


namespace webots_ros
{

struct node_get_string
{

typedef node_get_stringRequest Request;
typedef node_get_stringResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_get_string
} // namespace webots_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_ros::node_get_string > {
  static const char* value()
  {
    return "c228a96d2fd1b19a66eec886dc998e05";
  }

  static const char* value(const ::webots_ros::node_get_string&) { return value(); }
};

template<>
struct DataType< ::webots_ros::node_get_string > {
  static const char* value()
  {
    return "webots_ros/node_get_string";
  }

  static const char* value(const ::webots_ros::node_get_string&) { return value(); }
};


// service_traits::MD5Sum< ::webots_ros::node_get_stringRequest> should match
// service_traits::MD5Sum< ::webots_ros::node_get_string >
template<>
struct MD5Sum< ::webots_ros::node_get_stringRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_ros::node_get_string >::value();
  }
  static const char* value(const ::webots_ros::node_get_stringRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_ros::node_get_stringRequest> should match
// service_traits::DataType< ::webots_ros::node_get_string >
template<>
struct DataType< ::webots_ros::node_get_stringRequest>
{
  static const char* value()
  {
    return DataType< ::webots_ros::node_get_string >::value();
  }
  static const char* value(const ::webots_ros::node_get_stringRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_ros::node_get_stringResponse> should match
// service_traits::MD5Sum< ::webots_ros::node_get_string >
template<>
struct MD5Sum< ::webots_ros::node_get_stringResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_ros::node_get_string >::value();
  }
  static const char* value(const ::webots_ros::node_get_stringResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_ros::node_get_stringResponse> should match
// service_traits::DataType< ::webots_ros::node_get_string >
template<>
struct DataType< ::webots_ros::node_get_stringResponse>
{
  static const char* value()
  {
    return DataType< ::webots_ros::node_get_string >::value();
  }
  static const char* value(const ::webots_ros::node_get_stringResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_ROS_MESSAGE_NODE_GET_STRING_H
