// Generated by gencpp from file webots_ros/node_set_joint_position.msg
// DO NOT EDIT!


#ifndef WEBOTS_ROS_MESSAGE_NODE_SET_JOINT_POSITION_H
#define WEBOTS_ROS_MESSAGE_NODE_SET_JOINT_POSITION_H

#include <ros/service_traits.h>


#include <webots_ros/node_set_joint_positionRequest.h>
#include <webots_ros/node_set_joint_positionResponse.h>


namespace webots_ros
{

struct node_set_joint_position
{

typedef node_set_joint_positionRequest Request;
typedef node_set_joint_positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct node_set_joint_position
} // namespace webots_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::webots_ros::node_set_joint_position > {
  static const char* value()
  {
    return "5c6d60bc617f1348200743f9a8544085";
  }

  static const char* value(const ::webots_ros::node_set_joint_position&) { return value(); }
};

template<>
struct DataType< ::webots_ros::node_set_joint_position > {
  static const char* value()
  {
    return "webots_ros/node_set_joint_position";
  }

  static const char* value(const ::webots_ros::node_set_joint_position&) { return value(); }
};


// service_traits::MD5Sum< ::webots_ros::node_set_joint_positionRequest> should match
// service_traits::MD5Sum< ::webots_ros::node_set_joint_position >
template<>
struct MD5Sum< ::webots_ros::node_set_joint_positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::webots_ros::node_set_joint_position >::value();
  }
  static const char* value(const ::webots_ros::node_set_joint_positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_ros::node_set_joint_positionRequest> should match
// service_traits::DataType< ::webots_ros::node_set_joint_position >
template<>
struct DataType< ::webots_ros::node_set_joint_positionRequest>
{
  static const char* value()
  {
    return DataType< ::webots_ros::node_set_joint_position >::value();
  }
  static const char* value(const ::webots_ros::node_set_joint_positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::webots_ros::node_set_joint_positionResponse> should match
// service_traits::MD5Sum< ::webots_ros::node_set_joint_position >
template<>
struct MD5Sum< ::webots_ros::node_set_joint_positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::webots_ros::node_set_joint_position >::value();
  }
  static const char* value(const ::webots_ros::node_set_joint_positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::webots_ros::node_set_joint_positionResponse> should match
// service_traits::DataType< ::webots_ros::node_set_joint_position >
template<>
struct DataType< ::webots_ros::node_set_joint_positionResponse>
{
  static const char* value()
  {
    return DataType< ::webots_ros::node_set_joint_position >::value();
  }
  static const char* value(const ::webots_ros::node_set_joint_positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WEBOTS_ROS_MESSAGE_NODE_SET_JOINT_POSITION_H
