// Generated by gencpp from file webots_ros/RecognitionObjects.msg
// DO NOT EDIT!


#ifndef WEBOTS_ROS_MESSAGE_RECOGNITIONOBJECTS_H
#define WEBOTS_ROS_MESSAGE_RECOGNITIONOBJECTS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <webots_ros/RecognitionObject.h>

namespace webots_ros
{
template <class ContainerAllocator>
struct RecognitionObjects_
{
  typedef RecognitionObjects_<ContainerAllocator> Type;

  RecognitionObjects_()
    : header()
    , objects()  {
    }
  RecognitionObjects_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::webots_ros::RecognitionObject_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::webots_ros::RecognitionObject_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::webots_ros::RecognitionObjects_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::webots_ros::RecognitionObjects_<ContainerAllocator> const> ConstPtr;

}; // struct RecognitionObjects_

typedef ::webots_ros::RecognitionObjects_<std::allocator<void> > RecognitionObjects;

typedef boost::shared_ptr< ::webots_ros::RecognitionObjects > RecognitionObjectsPtr;
typedef boost::shared_ptr< ::webots_ros::RecognitionObjects const> RecognitionObjectsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::webots_ros::RecognitionObjects_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::webots_ros::RecognitionObjects_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::webots_ros::RecognitionObjects_<ContainerAllocator1> & lhs, const ::webots_ros::RecognitionObjects_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::webots_ros::RecognitionObjects_<ContainerAllocator1> & lhs, const ::webots_ros::RecognitionObjects_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace webots_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::webots_ros::RecognitionObjects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::webots_ros::RecognitionObjects_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webots_ros::RecognitionObjects_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::webots_ros::RecognitionObjects_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webots_ros::RecognitionObjects_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::webots_ros::RecognitionObjects_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::webots_ros::RecognitionObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ac0ec54e563936d28b7dec5cf26184c3";
  }

  static const char* value(const ::webots_ros::RecognitionObjects_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xac0ec54e563936d2ULL;
  static const uint64_t static_value2 = 0x8b7dec5cf26184c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::webots_ros::RecognitionObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "webots_ros/RecognitionObjects";
  }

  static const char* value(const ::webots_ros::RecognitionObjects_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::webots_ros::RecognitionObjects_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"webots_ros/RecognitionObject[] objects\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: webots_ros/RecognitionObject\n"
"geometry_msgs/Vector3 position\n"
"geometry_msgs/Quaternion orientation\n"
"geometry_msgs/Vector3 position_on_image\n"
"geometry_msgs/Vector3 size_on_image\n"
"int32 number_of_colors\n"
"geometry_msgs/Vector3[] colors\n"
"string model\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::webots_ros::RecognitionObjects_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::webots_ros::RecognitionObjects_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RecognitionObjects_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::webots_ros::RecognitionObjects_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::webots_ros::RecognitionObjects_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "objects: ";
    if (v.objects.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::webots_ros::RecognitionObject_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.objects[i]);
    }
    if (v.objects.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // WEBOTS_ROS_MESSAGE_RECOGNITIONOBJECTS_H
